// ==========================================
// API ENDPOINT CONSTANTS
// ==========================================

export const ENDPOINTS = {
          AUTH: {
                    LOGIN: '/auth/login',
                    REGISTER: '/auth/register',
                    REGISTER_TRAINER: '/auth/register-trainer',
                    REFRESH: '/auth/refresh',
                    LOGOUT: '/auth/logout',
                    LOGOUT_ALL: '/auth/logout-all',
                    ME: '/auth/me',
                    CHANGE_PASSWORD: '/auth/change-password',
          },
          USERS: {
                    BASE: '/users',
                    BY_ID: (id: string) => `/users/${id}`,
                    STATISTICS: '/users/statistics',
                    SEARCH: '/users/search',
                    BY_ROLE: (role: string) => `/users/by-role/${role}`,
                    ACTIVATE: (id: string) => `/users/${id}/activate`,
                    DEACTIVATE: (id: string) => `/users/${id}/deactivate`,
          },
          MANAGERS: {
                    BASE: '/managers',
                    BY_ID: (id: string) => `/managers/${id}`,
                    PERMISSIONS: (id: string) => `/managers/${id}/permissions`,
                    REMOVE_PERMISSION: (id: string, specId: string) =>
                              `/managers/${id}/permissions/${specId}`,
          },
          TRAINERS: {
                    BASE: '/trainers',
                    BY_ID: (id: string) => `/trainers/${id}`,
                    ME: '/trainers/me',
                    APPROVED: '/trainers/approved',
                    PENDING: '/trainers/pending',
                    APPROVE: (id: string) => `/trainers/${id}/approve`,
                    REJECT: (id: string) => `/trainers/${id}/reject`,
                    STATISTICS: (id: string) => `/trainers/${id}/statistics`,
          },
          REQUIREMENTS: {
                    TRAINING: (type: string, id: string) => `/requirements/training/${type}/${id}`,
                    BY_ID: (id: string) => `/requirements/${id}`,
                    ENROLLMENT: (type: string, id: string) => `/requirements/enrollment/${type}/${id}`,
                    REVIEW: (subId: string) => `/requirements/enrollment/${subId}/review`,
                    PENDING: '/requirements/pending',
                    CHECK: (type: string, id: string) => `/requirements/check/${type}/${id}`,
          },
          SPECIALIZATIONS: {
                    BASE: '/specializations',
                    BY_ID: (id: string) => `/specializations/${id}`,
                    STATISTICS: (id: string) => `/specializations/${id}/statistics`,
                    ACTIVATE: (id: string) => `/specializations/${id}/activate`,
                    DEACTIVATE: (id: string) => `/specializations/${id}/deactivate`,
          },
          WORKSHOPS: {
                    BASE: '/workshops',
                    BY_ID: (id: string) => `/workshops/${id}`,
                    UPCOMING: '/workshops/upcoming',
                    PENDING: '/workshops/pending',
                    MY_WORKSHOPS: '/workshops/my-workshops',
                    BOOKMARKED: '/workshops/bookmarked',
                    BY_TRAINER: (id: string) => `/workshops/trainer/${id}`,
                    REVIEW: (id: string) => `/workshops/${id}/review`,
                    STATUS: (id: string) => `/workshops/${id}/status`,
                    STATISTICS: (id: string) => `/workshops/${id}/statistics`,
                    IS_FULL: (id: string) => `/workshops/${id}/is-full`,
                    SYLLABUS: (id: string) => `/workshops/${id}/syllabus`,
                    SECTIONS: (id: string) => `/workshops/${id}/sections`,
                    SECTION: (sectionId: string) => `/workshops/sections/${sectionId}`,
                    REORDER_SECTIONS: (id: string) => `/workshops/${id}/sections/reorder`,
                    LESSONS: (sectionId: string) => `/workshops/sections/${sectionId}/lessons`,
                    LESSON: (lessonId: string) => `/workshops/lessons/${lessonId}`,
                    REORDER_LESSONS: (sectionId: string) => `/workshops/sections/${sectionId}/lessons/reorder`,
          },
          BOOKINGS: {
                    BASE: '/bookings',
                    BY_ID: (id: string) => `/bookings/${id}`,
                    MY_BOOKINGS: '/bookings/my-bookings',
                    WORKSHOP: (wid: string) => `/bookings/workshop/${wid}`,
                    CAN_BOOK: (wid: string) => `/bookings/workshop/${wid}/can-book`,
                    NEXT_SEAT: (wid: string) => `/bookings/workshop/${wid}/next-seat`,
                    CONFIRM: (id: string) => `/bookings/${id}/confirm`,
                    CANCEL: (id: string) => `/bookings/${id}/cancel`,
                    STATUS: (id: string) => `/bookings/${id}/status`,
                    ATTENDANCE: (id: string) => `/bookings/${id}/attendance`,
                    PAYMENT: (id: string) => `/bookings/${id}/payment`,
                    BULK_ATTENDANCE: '/bookings/bulk-attendance',
                    STATISTICS: '/bookings/statistics',
                    REVENUE: '/bookings/revenue',
          },
          NOTIFICATIONS: {
                    BASE: '/notifications',
                    UNREAD_COUNT: '/notifications/unread-count',
                    READ_ALL: '/notifications/read-all',
                    READ: (id: string) => `/notifications/${id}/read`,
                    DELETE: (id: string) => `/notifications/${id}`,
          },
          STATISTICS: {
                    DASHBOARD: '/statistics/dashboard',
                    WORKSHOPS: '/statistics/workshops',
                    TRAINERS: '/statistics/trainers',
                    TRAINER: (id: string) => `/statistics/trainers/${id}`,
          },
          UPLOADS: {
                    PROFILE_IMAGE: '/uploads/profile-image',
                    CV: '/uploads/cv',
                    WORKSHOP_COVER: '/uploads/workshop-cover',
                    MATERIALS: '/uploads/materials',
                    DOCUMENTS: '/uploads/documents',
                    DELETE: '/uploads',
          },
          COURSES: {
                    BASE: '/courses',
                    ALL: '/courses/all',
                    BY_ID: (id: string) => `/courses/${id}`,
                    MY_COURSES: '/courses/my-courses',
                    MY_ENROLLMENTS: '/courses/my-enrollments',
                    CONTENT: (id: string) => `/courses/${id}/content`,
                    ENROLL: (id: string) => `/courses/${id}/enroll`,
                    SECTIONS: (courseId: string) => `/courses/${courseId}/sections`,
                    SECTION: (courseId: string, sectionId: string) => `/courses/${courseId}/sections/${sectionId}`,
                    LESSONS: (courseId: string, sectionId: string) => `/courses/${courseId}/sections/${sectionId}/lessons`,
                    LESSON: (courseId: string, lessonId: string) => `/courses/${courseId}/lessons/${lessonId}`,
                    PENDING_ENROLLMENTS: '/courses/enrollments/pending',
                    CONFIRM_ENROLLMENT: (enrollmentId: string) => `/courses/enrollments/${enrollmentId}/confirm`,
                    UPLOAD_MEDIA: '/courses/upload/media',
                    PROGRESS: (courseId: string) => `/courses/${courseId}/progress`,
                    LESSON_COMPLETE: (courseId: string, lessonId: string) => `/courses/${courseId}/progress/${lessonId}/complete`,
                    LESSON_POSITION: (courseId: string, lessonId: string) => `/courses/${courseId}/progress/${lessonId}/position`,
                    REVIEW: (courseId: string) => `/courses/${courseId}/review`,
                    MY_REVIEW: (courseId: string) => `/courses/${courseId}/review/me`,
          },
} as const;
